name: First Automation

on: 
    push:
        branches:
            - main

jobs:
    good:
        runs-on: ubuntu-latest
        steps:
              - name: Hello
                run: echo "Hello World"

    bye:
        runs-on: ubuntu-latest
        steps:
            -   name: Bye
                run: echo "Good bye"
